project:
  type: website

website:
  title: "JuliaSpacePhysics"
  site-url: https://juliaspacephysics.github.io
  site-path: "/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Ecosystem
        href: ecosystem/
      - text: Tutorials
        href: tutorials/
    tools:
      - icon: github
        text: GitHub
        href: https://github.com/JuliaSpacePhysics
  back-to-top-navigation: true
  repo-url: https://github.com/JuliaSpacePhysics/juliaspacephysics.github.io/
  repo-actions: [edit, issue]

format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: true
    code-tools: true
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <script type="application/ld+json">
          {
            "@context" : "https://schema.org",
            "@type" : "WebSite",
            "name" : "JuliaSpacePhysics",
            "alternateName": "Space Physics in Julia",
            "url" : "https://juliaspacephysics.github.io/",
          }
          </script>

# Global Variables to use in any qmd files using:
# {{< meta site-url >}}
site-url: https://juliaspacephysics.github.io

execute:
  freeze: auto  # re-render only when source changes

engines: ['julia']