[deps]
CDAWeb = "950ff2a9-823f-469c-91a7-754a5d85edca"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
HAPIClient = "0ce0b37c-8851-4c5b-98a3-e691a5f19c53"
PySPEDAS = "668d2cef-03a7-4c36-a521-7d1c6ddc8846"
SpaceDataModel = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
SpacePhysicsMakie = "0c28ffd8-ae30-4a56-b2e4-f8332c621ad2"
Speasy = "09b745ad-c67d-442f-94a6-c7f4d1e4d861"

[compat]
Speasy = "0.4.8"
